# Generated by Django 3.1.2 on 2020-10-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=12)),
                ('address1', models.CharField(max_length=1024)),
                ('address2', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=1024)),
                ('country', models.CharField(max_length=3)),
                ('zip_code', models.CharField(max_length=12)),
                ('dob', models.DateField()),
            ],
        ),
    ]
