# Generated by Django 3.1.2 on 2020-10-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insured',
            name='ssn',
            field=models.IntegerField(default=99999999),
        ),
        migrations.AlterField(
            model_name='insured',
            name='phone_number',
            field=models.IntegerField(default=99999999),
        ),
        migrations.AlterField(
            model_name='insured',
            name='zip_code',
            field=models.IntegerField(default=999999),
        ),
    ]
